#pragma once

#include "sdk.h"

typedef struct D3DMATRIX
{
	float m[4][4];
} D3DMATRIX , *LPD3DMATRIX;

namespace HookIndexSDK
{
	enum IVEngineClient
	{
		GetIntersectingSurfaces ,
		GetLightForPoint ,
		TraceLineMaterialAndLighting ,
		ParseFile ,
		FileCopy ,
		GetScreenSize ,
		ServerCmd ,
		ClientCmd ,
		GetPlayerInfo ,
		GetPlayerForUserID ,
		TextMessageGet ,
		Con_IsVisible ,
		GetLocalPlayer ,
		LoadModel ,
		GetLastTimeStamp ,
		GetSentence ,
		GetSentenceLength ,
		IsStreaming ,
		GetViewAngles ,
		SetViewAngles ,
		GetMaxClients ,
		Key_LookupBinding ,
		Key_BindingForKey ,
		Key_SetBinding ,
		StartKeyTrapMode ,
		CheckDoneKeyTrapping ,
		IsInGame ,
		IsConnected ,
		IsDrawingLoadingImage ,
		HideLoadingPlaque ,
		Con_NPrintf ,
		Con_NXPrintf ,
		IsBoxVisible ,
		IsBoxInViewCluster ,
		CullBox ,
		Sound_ExtraUpdate ,
		GetGameDirectory ,
		WorldToScreenMatrix ,
		WorldToViewMatrix ,
		GameLumpVersion ,
		GameLumpSize ,
		LoadGameLump ,
		LevelLeafCount ,
		GetBSPTreeQuery ,
		LinearToGamma ,
		LightStyleValue ,
		ComputeDynamicLighting ,
		GetAmbientLightColor ,
		GetDXSupportLevel ,
		SupportsHDR ,
		Mat_Stub ,
		GetChapterName ,
		GetLevelName ,
		GetLevelNameShort ,
		GetMapGroupName ,
		GetVoiceTweakAPI ,
		SetVoiceCasterID ,
		EngineStats_BeginFrame ,
		EngineStats_EndFrame ,
		FireEvents ,
		GetLeavesArea ,
		DoesBoxTouchAreaFrustum ,
		GetFrustumList ,
		ShouldUseAreaFrustum ,
		SetAudioState ,
		SentenceGroupPick ,
		SentenceGroupPickSequential ,
		SentenceIndexFromName ,
		SentenceNameFromIndex ,
		SentenceGroupIndexFromName ,
		SentenceGroupNameFromIndex ,
		SentenceLength ,
		ComputeLighting ,
		ActivateOccluder ,
		IsOccluded ,
		GetOcclusionViewId ,
		SaveAllocMemory ,
		SaveFreeMemory ,
		GetNetChannelInfo ,
		DebugDrawPhysCollide ,
		CheckPoint ,
		DrawPortals ,
		IsPlayingDemo ,
		IsRecordingDemo ,
		IsPlayingTimeDemo ,
		GetDemoRecordingTick ,
		GetDemoPlaybackTick ,
		GetDemoPlaybackStartTick ,
		GetDemoPlaybackTimeScale ,
		GetDemoPlaybackTotalTicks ,
		IsPaused ,
		GetTimescale ,
		IsTakingScreenshot ,
		IsHLTV ,
		IsLevelMainMenuBackground ,
		GetMainMenuBackgroundName ,
		SetOcclusionParameters ,
		GetUILanguage ,
		IsSkyboxVisibleFromPoint ,
		GetMapEntitiesString ,
		IsInEditMode ,
		GetScreenAspectRatio ,
		REMOVED_SteamRefreshLogin ,
		REMOVED_SteamProcessCall ,
		GetEngineBuildNumber ,
		GetProductVersionString ,
		GrabPreColorCorrectedFrame ,
		IsHammerRunning ,
		ExecuteClientCmd ,
		MapHasHDRLighting ,
		MapHasLightMapAlphaData ,
		GetAppID ,
		GetLightForPointFast ,
		ClientCmd_Unrestricted1 ,
		ClientCmd_Unrestricted2 ,
		SetRestrictServerCommands ,
		SetRestrictClientCommands ,
		SetOverlayBindProxy ,
		CopyFrameBufferToMaterial ,
		ReadConfiguration ,
		SetAchievementMgr ,
		GetAchievementMgr ,
		MapLoadFailed ,
		SetMapLoadFailed ,
		IsLowViolence ,
		GetMostRecentSaveGame ,
		SetMostRecentSaveGame ,
		StartXboxExitingProcess ,
		IsSaveInProgress ,
		IsAutoSaveDangerousInProgress ,
		OnStorageDeviceAttached ,
		OnStorageDeviceDetached ,
		GetSaveDirName ,
		WriteScreenshot ,
		ResetDemoInterpolation ,
		GetActiveSplitScreenPlayerSlot ,
		SetActiveSplitScreenPlayerSlot ,
		SetLocalPlayerIsResolvable ,
		IsLocalPlayerResolvable ,
		GetSplitScreenPlayer ,
		IsSplitScreenActive ,
		IsValidSplitScreenSlot ,
		FirstValidSplitScreenSlot ,
		NextValidSplitScreenSlot ,
		GetSinglePlayerSharedMemorySpace ,
		ComputeLightingCube ,
		RegisterDemoCustomDataCallback ,
		RecordDemoCustomData ,
		SetPitchScale ,
		GetPitchScale ,
		LoadFilmmaker ,
		UnloadFilmmaker ,
		SetLeafFlag ,
		RecalculateBSPLeafFlags ,
		DSPGetCurrentDASRoomNew ,
		DSPGetCurrentDASRoomChanged ,
		DSPGetCurrentDASRoomSkyAbove ,
		DSPGetCurrentDASRoomSkyPercent ,
		SetMixGroupOfCurrentMixer ,
		GetMixLayerIndex ,
		SetMixLayerLevel ,
		GetMixGroupIndex ,
		SetMixLayerTriggerFactor1 ,
		SetMixLayerTriggerFactor2 ,
		IsCreatingReslist ,
		IsCreatingXboxReslist ,
		SetTimescale ,
		SetGamestatsData ,
		GetGamestatsData ,
		GetMouseDelta ,
		Key_LookupBindingEx ,
		Key_CodeForBinding ,
		UpdateDAndELights ,
		GetBugSubmissionCount ,
		ClearBugSubmissionCount ,
		DoesLevelContainWater ,
		GetServerSimulationFrameTime ,
		SolidMoved ,
		TriggerMoved ,
		ComputeLeavesConnected ,
		IsInCommentaryMode ,
		SetBlurFade ,
		IsTransitioningToLoad ,
		SearchPathsChangedAfterInstall ,
		ConfigureSystemLevel ,
		SetConnectionPassword ,
		GetSteamAPIContext ,
		SubmitStatRecord ,
		ServerCmdKeyValues ,
		SpherePaintSurface ,
		HasPaintmap ,
		EnablePaintmapRender ,
		SphereTracePaintSurface ,
		RemoveAllPaint ,
		PaintAllSurfaces ,
		RemovePaint ,
		IsActiveApp ,
		IsClientLocalToActiveServer ,
		TickProgressBar ,
		GetInputContext ,
		GetStartupImage ,
		IsUsingLocalNetworkBackdoor ,
		SaveGame ,
		GetGenericMemoryStats ,
		GameHasShutdownAndFlushedMemory ,
		GetLastAcknowledgedCommand ,
		FinishContainerWrites ,
		FinishAsyncSave ,
		GetServerTick ,
		GetModDirectory ,
		AudioLanguageChanged ,
		IsAutoSaveInProgress ,
		StartLoadingScreenForCommand ,
		StartLoadingScreenForKeyValues ,
		SOSSetOpvarFloat ,
		SOSGetOpvarFloat ,
		IsSubscribedMap ,
		IsFeaturedMap ,
		GetDemoPlaybackParameters ,
		GetClientVersion ,
		IsDemoSkipping ,
		SetDemoImportantEventData ,
		ClearEvents ,
		GetSafeZoneXMin ,
		IsVoiceRecording ,
		ForceVoiceRecordOn ,
		IsReplay
	};

	enum IBaseClientDLL
	{
		Connect ,
		Disconnect ,
		Init ,
		PostInit ,
		Shutdown ,
		LevelInitPreEntity ,
		LevelInitPostEntity ,
		LevelShutdown ,
		GetAllClasses ,
		HudVidInit ,
		HudProcessInput ,
		HudUpdate ,
		HudReset ,
		HudText ,
		ShouldDrawDropdownConsole ,
		IN_ActivateMouse ,
		IN_DeactivateMouse ,
		IN_Accumulate ,
		IN_ClearStates ,
		IN_IsKeyDown ,
		IN_KeyEvent ,
		CreateMove ,
		ExtraMouseSample ,
		WriteUsercmdDeltaToBuffer ,
		EncodeUserCmdToBuffer ,
		DecodeUserCmdFromBuffer ,
		View_Render ,
		RenderView ,
		View_Fade ,
		SetCrosshairAngle ,
		InitSprite ,
		ShutdownSprite ,
		GetSpriteSize ,
		VoiceStatus ,
		PlayerAudible ,
		InstallStringTableCallback ,
		FrameStageNotify ,
		DispatchUserMessage
	};

	enum ISurface
	{
		DrawSetColor1 = 14 ,
		DrawSetColor2 = 15 ,
		DrawFilledRect = 16 ,
		DrawOutlinedRect = 18 ,
		DrawLine = 19 ,
		DrawSetTextFont = 23 ,
		DrawSetTextColor = 24 ,
		DrawSetTextPos = 26 ,
		DrawPrintText = 28 ,
		FontCreate = 71 ,
		SetFontGlyphSet = 72 ,
		GetTextSize = 79
	};

	enum IPanel
	{
		IsVisible = 15 ,
		GetName = 36 ,
		PaintTraverse = 41
	};

	enum IClientMode
	{
		CL_CreateMove = 24
	};

	enum IEngineSound
	{
		PrecacheSound ,
		IsSoundPrecached ,
		PrefetchSound ,
		IsLoopingSound ,
		GetSoundDuration ,
		EmitSound1 ,
		EmitSound2 ,
		EmitSentenceByIndex ,
		StopSound ,
		StopAllSounds
	};

	enum D3D9
	{
		QueryInterface ,
		AddRef ,
		Release ,
		TestCooperativeLevel ,
		GetAvailableTextureMem ,
		EvictManagedResources ,
		GetDirect3D ,
		GetDeviceCaps ,
		GetDisplayMode ,
		GetCreationParameters ,
		SetCursorProperties ,
		SetCursorPosition ,
		ShowCursor ,
		CreateAdditionalSwapChain ,
		GetSwapChain ,
		GetNumberOfSwapChains ,
		Reset ,
		Present ,
		GetBackBuffer ,
		GetRasterStatus ,
		SetDialogBoxMode ,
		SetGammaRamp ,
		GetGammaRamp ,
		CreateTexture ,
		CreateVolumeTexture ,
		CreateCubeTexture ,
		CreateVertexBuffer ,
		CreateIndexBuffer ,
		CreateRenderTarget ,
		CreateDepthStencilSurface ,
		UpdateSurface ,
		UpdateTexture ,
		GetRenderTargetData ,
		GetFrontBufferData ,
		StretchRect ,
		ColorFill ,
		CreateOffscreenPlainSurface ,
		SetRenderTarget ,
		GetRenderTarget ,
		SetDepthStencilSurface ,
		GetDepthStencilSurface ,
		BeginScene ,
		EndScene ,
		Clear ,
		SetTransform ,
		GetTransform ,
		MultiplyTransform ,
		SetViewport ,
		GetViewport ,
		SetMaterial ,
		GetMaterial ,
		SetLight ,
		GetLight ,
		LightEnable ,
		GetLightEnable ,
		SetClipPlane ,
		GetClipPlane ,
		SetRenderState ,
		GetRenderState ,
		CreateStateBlock ,
		BeginStateBlock ,
		EndStateBlock ,
		SetClipStatus ,
		GetClipStatus ,
		GetTexture ,
		SetTexture ,
		GetTextureStageState ,
		SetTextureStageState ,
		GetSamplerState ,
		SetSamplerState ,
		ValidateDevice ,
		SetPaletteEntries ,
		GetPaletteEntries ,
		SetCurrentTexturePalette ,
		GetCurrentTexturePalette ,
		SetScissorRect ,
		GetScissorRect ,
		SetSoftwareVertexProcessing ,
		GetSoftwareVertexProcessing ,
		SetNPatchMode ,
		GetNPatchMode ,
		DrawPrimitive ,
		DrawIndexedPrimitive ,
		DrawPrimitiveUP ,
		DrawIndexedPrimitiveUP ,
		ProcessVertices ,
		CreateVertexDeclaration ,
		SetVertexDeclaration ,
		GetVertexDeclaration ,
		SetFVF ,
		GetFVF ,
		CreateVertexShader ,
		SetVertexShader ,
		GetVertexShader ,
		SetVertexShaderConstantF ,
		GetVertexShaderConstantF ,
		SetVertexShaderConstantI ,
		GetVertexShaderConstantI ,
		SetVertexShaderConstantB ,
		GetVertexShaderConstantB ,
		SetStreamSource ,
		GetStreamSource ,
		SetStreamSourceFreq ,
		GetStreamSourceFreq ,
		SetIndices ,
		GetIndices ,
		CreatePixelShader ,
		SetPixelShader ,
		GetPixelShader ,
		SetPixelShaderConstantF ,
		GetPixelShaderConstantF ,
		SetPixelShaderConstantI ,
		GetPixelShaderConstantI ,
		SetPixelShaderConstantB ,
		GetPixelShaderConstantB ,
		DrawRectPatch ,
		DrawTriPatch ,
		DeletePatch ,
		CreateQuery
	};
}

enum PLAYER_TEAM
{
	TEAM_SPEC = 1 ,
	TEAM_TT ,
	TEAM_CT
};

enum WEAPON_TYPE
{
	WEAPON_TYPE_PISTOL ,
	WEAPON_TYPE_SHOTGUN ,
	WEAPON_TYPE_SNIPER ,
	WEAPON_TYPE_GRENADE ,
	WEAPON_TYPE_KNIFE ,
	WEAPON_TYPE_C4 ,
	WEAPON_TYPE_UNKNOWN ,
};

enum ITEM_INDEX
{
	WEAPON_NONE = 0,
	WEAPON_DEAGLE = 1 ,
	WEAPON_ELITE = 2 ,
	WEAPON_FIVESEVEN = 3 ,
	WEAPON_GLOCK = 4 ,
	WEAPON_AK47 = 7 ,
	WEAPON_AUG = 8 ,
	WEAPON_AWP = 9 ,
	WEAPON_FAMAS = 10 ,
	WEAPON_G3SG1 = 11 ,
	WEAPON_GALILAR = 13 ,
	WEAPON_M249 = 14 ,
	WEAPON_M4A1 = 16 ,
	WEAPON_MAC10 = 17 ,
	WEAPON_P90 = 19 ,
	WEAPON_UMP45 = 24 ,
	WEAPON_XM1014 = 25 ,
	WEAPON_BIZON = 26 ,
	WEAPON_MAG7 = 27 ,
	WEAPON_NEGEV = 28 ,
	WEAPON_SAWEDOFF = 29 ,
	WEAPON_TEC9 = 30 ,
	WEAPON_TASER = 31 ,
	WEAPON_HKP2000 = 32 ,
	WEAPON_MP7 = 33 ,
	WEAPON_MP9 = 34 ,
	WEAPON_NOVA = 35 ,
	WEAPON_P250 = 36 ,
	WEAPON_SCAR20 = 38 ,
	WEAPON_SG553 = 39 ,
	WEAPON_SSG08 = 40 ,
	WEAPON_KNIFE = 42 ,
	WEAPON_FLASHBANG = 43 ,
	WEAPON_HEGRENADE = 44 ,
	WEAPON_SMOKEGRENADE = 45 ,
	WEAPON_MOLOTOV = 46 ,
	WEAPON_DECOY = 47 ,
	WEAPON_INCGRENADE = 48 ,
	WEAPON_C4 = 49 ,
	WEAPON_KNIFE_T = 59 ,
	WEAPON_M4A1_SILENCER = 60 ,
	WEAPON_USP_SILENCER = 61 ,
	WEAPON_CZ75A = 63 ,
	WEAPON_REVOLVER = 64 ,
	WEAPON_KNIFE_BAYONET = 500 ,
	WEAPON_KNIFE_FLIP = 505 ,
	WEAPON_KNIFE_GUT = 506 ,
	WEAPON_KNIFE_KARAMBIT = 507 ,
	WEAPON_KNIFE_M9_BAYONET = 508 ,
	WEAPON_KNIFE_TACTICAL = 509 ,
	WEAPON_KNIFE_FALCHION = 512 ,
	WEAPON_KNIFE_SURVIVAL_BOWIE = 514 ,
	WEAPON_KNIFE_BUTTERFLY = 515 ,
	WEAPON_KNIFE_PUSH = 516 ,
	WEAPON_MAX = 517
};

enum CLIENT_CLASS_ID
{
	CC_CAI_BaseNPC = 0,
	CC_CAK47 = 1,
	CC_CBaseAnimating = 2,
	CC_CBaseAnimatingOverlay = 3,
	CC_CBaseAttributableItem = 4,
	CC_CBaseButton = 5,
	CC_CBaseCombatCharacter = 6,
	CC_CBaseCombatWeapon = 7,
	CC_CBaseCSGrenade = 8,
	CC_CBaseCSGrenadeProjectile = 9,
	CC_CBaseDoor = 10,
	CC_CBaseEntity = 11,
	CC_CBaseFlex = 12,
	CC_CBaseGrenade = 13,
	CC_CBaseParticleEntity = 14,
	CC_CBasePlayer = 15,
	CC_CBasePropDoor = 16,
	CC_CBaseTeamObjectiveResource = 17,
	CC_CBaseTempEntity = 18,
	CC_CBaseToggle = 19,
	CC_CBaseTrigger = 20,
	CC_CBaseViewModel = 21,
	CC_CBaseVPhysicsTrigger = 22,
	CC_CBaseWeaponWorldModel = 23,
	CC_CBeam = 24,
	CC_CBeamSpotlight = 25,
	CC_CBoneFollower = 26,
	CC_CBreakableProp = 27,
	CC_CBreakableSurface = 28,
	CC_CC4 = 29,
	CC_CCascadeLight = 30,
	CC_CChicken = 31,
	CC_CColorCorrection = 32,
	CC_CColorCorrectionVolume = 33,
	CC_CCSGameRulesProxy = 34,
	CC_CCSPlayer = 35,
	CC_CCSPlayerResource = 36,
	CC_CCSRagdoll = 37,
	CC_CCSTeam = 38,
	CC_CDEagle = 39,
	CC_CDecoyGrenade = 40,
	CC_CDecoyProjectile = 41,
	CC_CDynamicLight = 42,
	CC_CDynamicProp = 43,
	CC_CEconEntity = 44,
	CC_CEconWearable = 45,
	CC_CEmbers = 46,
	CC_CEntityDissolve = 47,
	CC_CEntityFlame = 48,
	CC_CEntityFreezing = 49,
	CC_CEntityParticleTrail = 50,
	CC_CEnvAmbientLight = 51,
	CC_CEnvDetailController = 52,
	CC_CEnvDOFController = 53,
	CC_CEnvParticleScript = 54,
	CC_CEnvProjectedTexture = 55,
	CC_CEnvQuadraticBeam = 56,
	CC_CEnvScreenEffect = 57,
	CC_CEnvScreenOverlay = 58,
	CC_CEnvTonemapController = 59,
	CC_CEnvWind = 60,
	CC_CFEPlayerDecal = 61,
	CC_CFireCrackerBlast = 62,
	CC_CFireSmoke = 63,
	CC_CFireTrail = 64,
	CC_CFish = 65,
	CC_CFlashbang = 66,
	CC_CFogController = 67,
	CC_CFootstepControl = 68,
	CC_CFunc_Dust = 69,
	CC_CFunc_LOD = 70,
	CC_CFuncAreaPortalWindow = 71,
	CC_CFuncBrush = 72,
	CC_CFuncConveyor = 73,
	CC_CFuncLadder = 74,
	CC_CFuncMonitor = 75,
	CC_CFuncMoveLinear = 76,
	CC_CFuncOccluder = 77,
	CC_CFuncReflectiveGlass = 78,
	CC_CFuncRotating = 79,
	CC_CFuncSmokeVolume = 80,
	CC_CFuncTrackTrain = 81,
	CC_CGameRulesProxy = 82,
	CC_CHandleTest = 83,
	CC_CHEGrenade = 84,
	CC_CHostage = 85,
	CC_CHostageCarriableProp = 86,
	CC_CIncendiaryGrenade = 87,
	CC_CInferno = 88,
	CC_CInfoLadderDismount = 89,
	CC_CInfoOverlayAccessor = 90,
	CC_CItem_Healthshot = 91,
	CC_CKnife = 92,
	CC_CKnifeGG = 93,
	CC_CLightGlow = 94,
	CC_CMaterialModifyControl = 95,
	CC_CMolotovGrenade = 96,
	CC_CMolotovProjectile = 97,
	CC_CMovieDisplay = 98,
	CC_CParticleFire = 99,
	CC_CParticlePerformanceMonitor = 100,
	CC_CParticleSystem = 101,
	CC_CPhysBox = 102,
	CC_CPhysBoxMultiplayer = 103,
	CC_CPhysicsProp = 104,
	CC_CPhysicsPropMultiplayer = 105,
	CC_CPhysMagnet = 106,
	CC_CPlantedC4 = 107,
	CC_CPlasma = 108,
	CC_CPlayerResource = 109,
	CC_CPointCamera = 110,
	CC_CPointCommentaryNode = 111,
	CC_CPoseController = 112,
	CC_CPostProcessController = 113,
	CC_CPrecipitation = 114,
	CC_CPrecipitationBlocker = 115,
	CC_CPredictedViewModel = 116,
	CC_CProp_Hallucination = 117,
	CC_CPropDoorRotating = 118,
	CC_CPropJeep = 119,
	CC_CPropVehicleDriveable = 120,
	CC_CRagdollManager = 121,
	CC_CRagdollProp = 122,
	CC_CRagdollPropAttached = 123,
	CC_CRopeKeyframe = 124,
	CC_CSCAR17 = 125,
	CC_CSceneEntity = 126,
	CC_CSensorGrenade = 127,
	CC_CSensorGrenadeProjectile = 128,
	CC_CShadowControl = 129,
	CC_CSlideshowDisplay = 130,
	CC_CSmokeGrenade = 131,
	CC_CSmokeGrenadeProjectile = 132,
	CC_CSmokeStack = 133,
	CC_CSpatialEntity = 134,
	CC_CSpotlightEnd = 135,
	CC_CSprite = 136,
	CC_CSpriteOriented = 137,
	CC_CSpriteTrail = 138,
	CC_CStatueProp = 139,
	CC_CSteamJet = 140,
	CC_CSun = 141,
	CC_CSunlightShadowControl = 142,
	CC_CTeam = 143,
	CC_CTeamplayRoundBasedRulesProxy = 144,
	CC_CTEArmorRicochet = 145,
	CC_CTEBaseBeam = 146,
	CC_CTEBeamEntPoint = 147,
	CC_CTEBeamEnts = 148,
	CC_CTEBeamFollow = 149,
	CC_CTEBeamLaser = 150,
	CC_CTEBeamPoints = 151,
	CC_CTEBeamRing = 152,
	CC_CTEBeamRingPoint = 153,
	CC_CTEBeamSpline = 154,
	CC_CTEBloodSprite = 155,
	CC_CTEBloodStream = 156,
	CC_CTEBreakModel = 157,
	CC_CTEBSPDecal = 158,
	CC_CTEBubbles = 159,
	CC_CTEBubbleTrail = 160,
	CC_CTEClientProjectile = 161,
	CC_CTEDecal = 162,
	CC_CTEDust = 163,
	CC_CTEDynamicLight = 164,
	CC_CTEEffectDispatch = 165,
	CC_CTEEnergySplash = 166,
	CC_CTEExplosion = 167,
	CC_CTEFireBullets = 168,
	CC_CTEFizz = 169,
	CC_CTEFootprintDecal = 170,
	CC_CTEFoundryHelpers = 171,
	CC_CTEGaussExplosion = 172,
	CC_CTEGlowSprite = 173,
	CC_CTEImpact = 174,
	CC_CTEKillPlayerAttachments = 175,
	CC_CTELargeFunnel = 176,
	CC_CTEMetalSparks = 177,
	CC_CTEMuzzleFlash = 178,
	CC_CTEParticleSystem = 179,
	CC_CTEPhysicsProp = 180,
	CC_CTEPlantBomb = 181,
	CC_CTEPlayerAnimEvent = 182,
	CC_CTEPlayerDecal = 183,
	CC_CTEProjectedDecal = 184,
	CC_CTERadioIcon = 185,
	CC_CTEShatterSurface = 186,
	CC_CTEShowLine = 187,
	CC_CTesla = 188,
	CC_CTESmoke = 189,
	CC_CTESparks = 190,
	CC_CTESprite = 191,
	CC_CTESpriteSpray = 192,
	CC_CTest_ProxyToggle_Networkable = 193,
	CC_CTestTraceline = 194,
	CC_CTEWorldDecal = 195,
	CC_CTriggerPlayerMovement = 196,
	CC_CTriggerSoundOperator = 197,
	CC_CVGuiScreen = 198,
	CC_CVoteController = 199,
	CC_CWaterBullet = 200,
	CC_CWaterLODControl = 201,
	CC_CWeaponAug = 202,
	CC_CWeaponAWP = 203,
	CC_CWeaponBaseItem = 204,
	CC_CWeaponBizon = 205,
	CC_CWeaponCSBase = 206,
	CC_CWeaponCSBaseGun = 207,
	CC_CWeaponCycler = 208,
	CC_CWeaponElite = 209,
	CC_CWeaponFamas = 210,
	CC_CWeaponFiveSeven = 211,
	CC_CWeaponG3SG1 = 212,
	CC_CWeaponGalil = 213,
	CC_CWeaponGalilAR = 214,
	CC_CWeaponGlock = 215,
	CC_CWeaponHKP2000 = 216,
	CC_CWeaponM249 = 217,
	CC_CWeaponM3 = 218,
	CC_CWeaponM4A1 = 219,
	CC_CWeaponMAC10 = 220,
	CC_CWeaponMag7 = 221,
	CC_CWeaponMP5Navy = 222,
	CC_CWeaponMP7 = 223,
	CC_CWeaponMP9 = 224,
	CC_CWeaponNegev = 225,
	CC_CWeaponNOVA = 226,
	CC_CWeaponP228 = 227,
	CC_CWeaponP250 = 228,
	CC_CWeaponP90 = 229,
	CC_CWeaponSawedoff = 230,
	CC_CWeaponSCAR20 = 231,
	CC_CWeaponScout = 232,
	CC_CWeaponSG550 = 233,
	CC_CWeaponSG552 = 234,
	CC_CWeaponSG556 = 235,
	CC_CWeaponSSG08 = 236,
	CC_CWeaponTaser = 237,
	CC_CWeaponTec9 = 238,
	CC_CWeaponTMP = 239,
	CC_CWeaponUMP45 = 240,
	CC_CWeaponUSP = 241,
	CC_CWeaponXM1014 = 242,
	CC_CWorld = 243,
	CC_DustTrail = 244,
	CC_MovieExplosion = 245,
	CC_ParticleSmokeGrenade = 246,
	CC_RocketTrail = 247,
	CC_SmokeTrail = 248,
	CC_SporeExplosion = 249,
	CC_SporeTrail = 250,
	
};

template< typename Function > Function call_func( PVOID Base , DWORD Index )
{
	PDWORD* VTablePointer = (PDWORD*)Base;
	PDWORD VTableFunctionBase = *VTablePointer;
	DWORD dwAddress = VTableFunctionBase[Index];
	return (Function)( dwAddress );
}